version: '3'
services:

  api:
    build: 
      context: ./api
      args:
        - VERSION=local-docker-compose
    ports:
      - 8888:80
    environment:
      BACKEND: db+postgresql://user:password@db:5432/database
      BROKER: redis://redis:6379/0
    labels:
      traefik.enable: true
      traefik.http.routers.our-celery-manager-2.rule: Host(`our-celery-manager.localhost`)
      traefik.http.services.our-celery-manager-2.loadbalancer.server.port: 80
  
  worker:
    build:
      context: ./api
      args:
        - VERSION=local-docker-compose
    environment:
      BACKEND: db+postgresql://user:password@db:5432/database
      BROKER: redis://redis:6379/0
    command: "celery -A app.ocm_worker worker --loglevel=info"

  redis:
    image: redis
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=username:password  # Replace username and password with your own

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database

  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock