#
# Docker compose pour un env de dev rapide
#
version: '3'
services:
  api:
    build: api/.
    ports:
      - 8888:80
    environment:
      BACKEND: db+postgresql://user:password@db:5432/database
      BROKER: redis://redis:6379/0

  redis:
    image: redis
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=username:password  # Remplacez username et password par vos propres identifiants

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database