"""empty message

Revision ID: 4a7424b834ef
Revises: ea3f29edb363
Create Date: 2023-09-12 23:45:13.990022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7424b834ef'
down_revision: Union[str, None] = 'ea3f29edb363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloning_events', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True), schema='ocm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloning_events', 'created', schema='ocm')
    # ### end Alembic commands ###
