"""empty message

Revision ID: 89c2b3ba6408
Revises: d3c4969ca5a9
Create Date: 2023-09-12 23:31:50.324661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c2b3ba6408'
down_revision: Union[str, None] = 'd3c4969ca5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=155), nullable=False),
    sa.Column('clone', sa.String(length=155), nullable=False),
    sa.ForeignKeyConstraint(['clone'], ['celery_taskmeta.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task'], ['celery_taskmeta.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ocm'
    )
    op.drop_table('taskmeta', schema='ocm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskmeta',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ocm.taskmeta_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('command', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('from_task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_task_id'], ['celery_taskmeta.task_id'], name='taskmeta_from_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='taskmeta_pkey'),
    schema='ocm'
    )
    op.drop_table('cloning_events', schema='ocm')
    # ### end Alembic commands ###
