"""empty message

Revision ID: ea00ff9b8a90
Revises: 89c2b3ba6408
Create Date: 2023-09-12 23:39:31.276622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea00ff9b8a90'
down_revision: Union[str, None] = '89c2b3ba6408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cloning_events_clone_fkey', 'cloning_events', schema='ocm', type_='foreignkey')
    op.drop_constraint('cloning_events_task_fkey', 'cloning_events', schema='ocm', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cloning_events_task_fkey', 'cloning_events', 'celery_taskmeta', ['task'], ['task_id'], source_schema='ocm', ondelete='CASCADE')
    op.create_foreign_key('cloning_events_clone_fkey', 'cloning_events', 'celery_taskmeta', ['clone'], ['task_id'], source_schema='ocm', ondelete='CASCADE')
    # ### end Alembic commands ###
