"""empty message

Revision ID: ea3f29edb363
Revises: ea00ff9b8a90
Create Date: 2023-09-12 23:41:21.773320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3f29edb363'
down_revision: Union[str, None] = 'ea00ff9b8a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloning_events', sa.Column('task_id', sa.String(), nullable=False), schema='ocm')
    op.add_column('cloning_events', sa.Column('clone_id', sa.String(), nullable=False), schema='ocm')
    op.drop_column('cloning_events', 'clone', schema='ocm')
    op.drop_column('cloning_events', 'task', schema='ocm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloning_events', sa.Column('task', sa.VARCHAR(length=155), autoincrement=False, nullable=False), schema='ocm')
    op.add_column('cloning_events', sa.Column('clone', sa.VARCHAR(length=155), autoincrement=False, nullable=False), schema='ocm')
    op.drop_column('cloning_events', 'clone_id', schema='ocm')
    op.drop_column('cloning_events', 'task_id', schema='ocm')
    # ### end Alembic commands ###
